---
title: "Assignment - NB"
author: Hai Tran
Reviewer: Niek Navis

date: March 25, 2022
output:
   html_notebook:
    toc: true
    toc_depth: 2
---

```{r}
library(tidyverse)
library(dplyr)
library(caret)
library(tm)
library(wordcloud)
library(e1071)
```
---
In this assignment, I choose the dataset NB-fakenews.csv

## Business Understanding
Cluster and identify and filter fake news with the Naive Bayes model. 

## Data Understanding
```{r}
url <- "https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/data-mining-s2y2122-thtran942/master/datasets/NB-fakenews.csv"
rawDF <- read.csv (url)
view(rawDF)


rawDF <- rawDF %>% relocate(label, .before = text)
rawDF <- mutate(rawDF, label = recode(label,"0"= "real", "1"= "fake"))
head (rawDF)

rawDF$label <- rawDF$label %>% factor %>% relevel("fake")
class(rawDF$label)

fake <- rawDF %>% filter(label == "fake")
real <- rawDF %>% filter(label == "real")


wordcloud (spam$text, max.words = 20, scale = c(4, 0.8), colors= c("indianred1","indianred2","indianred3","indianred"))
wordcloud (ham$text, max.words = 20, scale = c(4, 0.8), colors= c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue"))
```

## Data Preparation
```{r}
rawCorpus <- Corpus(VectorSource(rawDF$text))
inspect(rawCorpus[1:3])


cleanCorpus <- rawCorpus %>% tm_map(tolower) %>% tm_map(removeNumbers)
cleanCorpus <- cleanCorpus %>% tm_map(tolower) %>% tm_map(removeWords, stopwords()) %>% tm_map(removePunctuation)
cleanCorpus <- cleanCorpus %>% tm_map(stripWhitespace)

tibble(Raw = rawCorpus$content[1:3], Clean = cleanCorpus$content[1:3])
cleanDTM <- cleanCorpus %>% DocumentTermMatrix
inspect(cleanDTM)


set.seed(1234)
trainIndex <- createDataPartition(rawDF$label, p = .75, 
                                  list = FALSE, 
                                  times = 1)
head(trainIndex)


trainDF <- rawDF[trainIndex, ]
testDF <- rawDF[-trainIndex, ]

trainCorpus <- cleanCorpus[trainIndex]
testCorpus <- cleanCorpus[-trainIndex]

trainDTM <- cleanDTM[trainIndex, ]
testDTM <- cleanDTM[-trainIndex, ]


freqWords <- trainDTM %>% findFreqTerms(50)
trainDTM <-  DocumentTermMatrix(trainCorpus, list(dictionary = freqWords))
testDTM <-  DocumentTermMatrix(testCorpus, list(dictionary = freqWords))


convert_counts <- function(x) {
  x <- ifelse(x > 0, 1, 0) %>% factor(levels = c(0,1), labels = c("No", "Yes"))
}


nColsDTM <- dim(trainDTM)[2]
trainDTM <- apply(trainDTM, MARGIN = 2, convert_counts)
testDTM <- apply(testDTM, MARGIN = 2, convert_counts)

head(trainDTM[,1:10])
```
## Modeling and Evaluation
```{r}
nbayesModel <-  naiveBayes(trainDTM, trainDF$label, laplace = 1)

predVec <- predict(nbayesModel, testDTM)
confusionMatrix(predVec, testDF$label, positive = "fake", dnn = c("Prediction", "True"))
```

